In [2]:
from sklearn.neighbors import KNeighborsClassifier
from ast import increment_lineno
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [6]:
for i in range(3, 10):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print('for KNN, when neighbor = ', i)
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

for KNN, when neighbor =  3
[[11  0  0]
 [ 0  8  1]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.89      0.94         9
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30

for KNN, when neighbor =  4
[[11  0  0]
 [ 0  8  1]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.89      0.94         9
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30

for KNN, when neighbor =  5
[[11  0  0]
 [ 0  8  1]
 [ 0  0 10]]
 

In [7]:
from KNN import KNN_batch
KNN_batch(X, y)

for KNN, when neighbor =  3
[[13  0  0]
 [ 0  5  2]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.71      0.83         7
 Iris-virginica       0.83      1.00      0.91        10

       accuracy                           0.93        30
      macro avg       0.94      0.90      0.91        30
   weighted avg       0.94      0.93      0.93        30

for KNN, when neighbor =  4
[[13  0  0]
 [ 0  6  1]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.86      0.92         7
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.95      0.96        30
   weighted avg       0.97      0.97      0.97        30

for KNN, when neighbor =  5
[[13  0  0]
 [ 0  5  2]
 [ 0  0 10]]
 

In [8]:
X.shape

(150, 4)

In [9]:
y.shape

(150,)

In [15]:
import xgboost as xgb
model = xgb.XGBClassifier(random_state=42)
model.fit(X_train, y_train)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

Note: you may need to restart the kernel to use updated packages.
